export const  GET_ALL_ORDERS_REQUEST="GET_ALL_ORDERS_REQUEST";
export const  GET_ALL_ORDERS_SUCCESS="GET_ALL_ORDERS_SUCCESS";
export const  GET_ALL_ORDERS_FAILURE="GET_ALL_ORDERS_FAILURE";

export const CONFIRMED_ORDER_REQUEST="CONFIRMED_ORDER_REQUEST";
export const CONFIRMED_ORDER_SUCCESS="CONFIRMED_ORDER_SUCCESS";
export const CONFIRMED_ORDER_FAILURE="CONFIRMED_ORDER_FAILURE";


export const DELIVERED_ORDER_REQUEST="DELIVERED_ORDER_REQUEST";
export const DELIVERED_ORDER_SUCCESS="DELIVERED_ORDER_SUCCESS";
export const DELIVERED_ORDER_FAILURE="DELIVERED_ORDER_FAILURE";

export const CANCELLED_ORDER_REQUEST="CANCELLED_ORDER_REQUEST";
export const CANCELLED_ORDER_SUCCESS="CANCELLED_ORDER_SUCCESS";
export const CANCELLED_ORDER_FAILURE="CANCELLED_ORDER_FAILURE";

export const SHIPED_ORDER_REQUEST="SHIPED_ORDER_REQUEST";
export const SHIPED_ORDER_SUCCESS="SHIPED_ORDER_SUCCESS";
export const SHIPED_ORDER_FAILURE="SHIPED_ORDER_FAILURE";

export  const DELETE_ORDER_REQUEST="DELETE_ORDER_REQUEST";
export  const DELETE_ORDER_SUCCESS="DELETE_ORDER_SUCCESS";
export  const DELETE_ORDER_FAILURE="DELETE_ORDER_FAILURE";


